### ISSUE TITLE
g:focalpoint_bg_fade has no effect

### ISSUE THREAD

**Issue by engeljh** [ShayHill/vim9-focalpoint#1]
It doesn't seem to matter what I set this variable to be in my .vimrc; nothing ever changes.  Is it just me?

**Comment by ShayHill** [comment]
Are you using Vim in the terminal? Vim9-focalpoint tries to find a color of the 256-color palette that approximates a mix of the background and foreground colors. Have to tried values like 0 or 1 as a test?

**Comment by ShayHill** [comment]
Another thing to test. New values are not calculated until you change colorscheme. Try switching between two colorschemes to see if you get the desired effect from g:focalpoint_bg_fade

**Comment by engeljh** [comment]
This is really strange.


  1.  It doesn't matter whether I'm in the terminal or in gvim.

  2.  When I open vim and split a window, the inactive window is shaded as expected.  And when I leave the active window, it becomes shaded as expected.  But the amount of shading is independent of g:focalpoint_bg_fade, even when that variable is 0 or 1.

  3.  When I change the color scheme, the shading disappears altogether.  And it doesn't return when I switch back to the original color scheme.

  4.  I thought that perhaps example-config.vim in the plugin directory was being sourced and overriding the settings in my .vimrc, but the behavior is the same when I remove the variable definition from my .vimrc and try to set it in example_config.vim

Thanks for your help,
Jon

________________________________

**Comment by ShayHill** [comment]
One more thing to check. Are you using any of these colorschemes: 'delek', 'habamax', 'industry', 'koehler', 'lunaperche', 'morning', 'pablo', 'peachpuff', 'quiet', 'retrobox', 'torte', 'wildcharm'.

If you're using any of those with the example configuration, the background color is set using the pmenu highlight group, NOT by blending the background and foreground colors per g:focalpoint_bg_fade.

A quick way to test is to set `:colorscheme delek` and see if you have a blue (using pmenu) or gray (blending fg and bg) background.

If that still doesn't address it, I'd like to have a look at your config.

**Comment by engeljh** [comment]
I'm not using any of those, but when I do use delek, the inactive background is blue, whether or not I comment out the lines in example_config.vim that tell it to use pmenu for that (and other) color schemes.

Do you want my entire .vimrc, or only the part dealing with your plugin?  That part is really simple:

"let g:focalpoint_bg_fade = 0.5
"let g:focalpoint_text_fade = 1.0
augroup ShadeNotCurrentWindow
  autocmd!
  autocmd WinEnter * setl wincolor=Normal
  autocmd WinLeave * setl wincolor=NormalNC
augroup END

The first two lines are commented out at present.

Thanks,
Jon

P.S.  I am using lightline, but don't need the status-line. Just to check, I got rid of all plugins except for yours, and the problem persisted.  The status line was dimmed properly after I changed colorschemes, but the windows themselves were not.


________________________________

**Comment by ShayHill** [comment]
I see now that I set `g:focalpoint_use_pmenu = v:true` as a default. I'm kind of torn wether to set that back because it fixes so many "broken" default Vim colorschemes (by giving them readable dropdown menus).

As for now, you can set something like this in your colorscheme:

```
g:focalpoint_use_pmenu = v:false
g:focalpoint_bg_fade = 0.70 
```

You'll have to then `:call FPReset` for the changes to take effect. This is what I have in my vimrc to have the best of both worlds:)

```
g:use_pmenu_to_shade = [
    'delek',
    'habamax',
    'industry',
    'koehler',
    'lunaperche',
    'morning',
    'pablo',
    'peachpuff',
    'quiet',
    'retrobox',
    'torte',
    'wildcharm',
]

augroup ResetStatuslineHiGroups
  autocmd!
  autocmd colorscheme * g:focalpoint_use_pmenu = index(g:use_pmenu_to_shade, g:colors_name) != -1 ? v:true : v:false | g:FPReset()
augroup END
```

That way I've got the nice pmenu colors to use when the colorscheme designers have set them. The rest of the time, `g:focalpoint_fp_fade` will work.

Does this address your issue?

**Comment by engeljh** [comment]
Yup, thanks!
________________________________
