### ISSUE TITLE
Add this plugin to Awesome-Vim9

### ISSUE THREAD

**Issue by engeljh** [ShayHill/vim9-focalpoint#2]
Not an issue, just a statement that you might want to add vim9-focalpoint to the "official" list of vim9 plugins at

https://github.com/saccarosium/awesome-vim9

Feel free to close the issue immediately, and sorry for bothering you if you're already aware of the site.

**Comment by ShayHill** [comment]
Thank you. I've submitted two pull requests with my vim9 plugins.
